### PR TITLE
implement try_from for &Value

### PR DESCRIPTION
**Pull request by glommer**
Very similar to Value and can use the same macro. Essentially induces a clone, because we can't try_from to slice anyway (no size).

### CODE REVIEW

**Comment by psarna** [comment]
Hm, not a huge fan of implicit cloning, since we have strings and vectors. What we can do for references is implementing a TryFrom between two refs, effectively allowing users to take a `&Value` and try transforming it into `&str`, `&String`, etc.

Here's how I imagine the implementation to look like:
```diff
diff --git a/hrana-client-proto/src/lib.rs b/hrana-client-proto/src/lib.rs
index b0e51b6..b5d50e7 100644
--- a/hrana-client-proto/src/lib.rs
+++ b/hrana-client-proto/src/lib.rs
@@ -331,10 +331,28 @@ macro_rules! impl_value_try_from {
     };
 }
 
+macro_rules! impl_value_try_from_ref {
+    ($variant: ident, $typename: ty) => {
+        impl<'a> TryFrom<&'a Value> for &'a $typename {
+            type Error = String;
+            fn try_from(v: &'a Value) -> Result<&'a $typename, Self::Error> {
+                match v {
+                    Value::$variant { value: ref v } => Ok(v),
+                    other => Err(format!(
+                        "cannot transform {other:?} to {}",
+                        stringify!($variant)
+                    )),
+                }
+            }
+        }
+    };
+}
+
 impl_value_try_from!(Text, String);
 
 impl_value_try_from!(Integer, i8);
 impl_value_try_from!(Integer, i16);
+
 impl_value_try_from!(Integer, i32);
 impl_value_try_from!(Integer, i64);
 impl_value_try_from!(Integer, u8);
@@ -345,3 +363,13 @@ impl_value_try_from!(Integer, u64);
 impl_value_try_from!(Float, f64);
 
 impl_value_try_from!(Blob, Vec<u8>);
+
+impl_value_try_from_ref!(Integer, i64);
+
+impl_value_try_from_ref!(Text, String);
+impl_value_try_from_ref!(Text, str);
+
+impl_value_try_from_ref!(Blob, Vec<u8>);
+impl_value_try_from_ref!(Blob, [u8]);
+
+impl_value_try_from_ref!(Float, f64);
```

Let me know what you think @glommer

**Comment by psarna** [comment]
With my suggested impl, you can transform into the inner type without cloning, because you only get a reference, e.g.:
```rust
    let v: &Value = &Value::Text{value: "hello there".to_string()};
    let v: &str = v.try_into().unwrap();
    println!("Value: {}", v);
```

**Comment by glommer** [comment]
I also am not a fan of implicit clone, but your impl would end up with a reference for integers, which is quite cumbersome.

I guess the only way is to have two different macros, one for integers and one for str and vec.

**Comment by glommer** [comment]
Let me know what you think of the implementation I am suggesting here.
It should cover both integers and strings by using a different macro for the latter.

**Comment by psarna** [comment]
yup, perfect

**Comment by psarna** [comment]
also, just released libsql-client-rs 0.24.3 which includes these changes

**Pull request merged**
